'use client';
import {useEffect,useState} from 'react';
export default function RebootControl(){
 const [state,setState]=useState(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[id,setId]=useState(null);
 async function load(){try{const r=await fetch('/api/reboot',{cache:'no-store'});if(!r.ok)throw Error('Device status unavailable.');setState(await r.json());}catch(e){setState(null);setError(e.message);}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t);},[]);
 async function reboot(){setBusy(true);setError('');const requestId=id||crypto.randomUUID();setId(requestId);try{const r=await fetch('/api/reboot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,action:confirm})});const d=await r.json();if(!r.ok)throw Error(d.error);setConfirm(false);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const c=state?.command;const expired=c?.status==='queued'&&Date.parse(c.expiresAt)<Date.now();
 const shuttingDown=c?.action==='shutdown';
 const message=shuttingDown?({queued:'Shutdown requested. Waiting for the Pi…',scheduled:'Shutdown command received. The Pi is shutting down; reconnect power to start it again.',completed:'Pi powered on again.',failed:'Shutdown failed. Check the Pi setup.'}[expired?'expired':c?.status]||'Shutdown request expired.'):expired?'Request expired; the Pi did not act on it.':({queued:'Reboot requested. Waiting for the Pi…',scheduled:'Restart scheduled. The Pi will reboot shortly, then reconnect.',completed:'Pi restarted and reconnected.',failed:'The Pi could not schedule the restart. Check its reboot setup.'}[c?.status]);
 const pending=c&&['queued','scheduled'].includes(c.status)&&Date.now()-Date.parse(c.createdAt)<180000;
 return <section className="monitoring-reset"><h2>Pi controls</h2><p>Restart or shut down the cellar Pi. Saved history is retained.</p>{message&&<p role="status">{message}</p>}{!state?.ready&&!pending&&<p className="muted">Reboot unavailable: the Pi is offline or its one-time setup is incomplete.</p>}{confirm?<div><p>{confirm==='shutdown'?'Shut down now? Logging and recording will stop immediately when the Pi receives this request (normally within 15 seconds). You must reconnect power to start it again.':'Reboot now? The Pi schedules a restart in one minute after receiving the request.'}</p><button disabled={busy} onClick={reboot}>{busy?'Requesting…':confirm==='shutdown'?'Confirm shutdown':'Confirm reboot'}</button>{' '}<button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div>:<div><button disabled={!state?.ready||pending} onClick={()=>{setConfirm("reboot");setId(null);setError('');}}>Reboot Pi…</button>{' '}<button disabled={!state?.shutdownReady||pending} onClick={()=>{setConfirm("shutdown");setId(null);setError('');}}>Shutdown Pi…</button>{state?.ready&&!state?.shutdownReady&&<p className="muted">Shutdown requires one-time setup on the Pi.</p>}</div>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
