'use client';
import {useEffect,useState} from 'react';
const titles={reboot:'reboot',shutdown:'shutdown',pause_camera:'pause camera',resume_camera:'resume camera'};
const descriptions={reboot:'Reboot now? The Pi schedules a restart in one minute after receiving the request.',shutdown:'Shut down now? Logging and recording stop when the Pi receives the request (normally within 15 seconds). Reconnect power to start it again.',pause_camera:'Pause camera recording? Temperature logging continues. Saved clips remain available and queued clips can finish uploading. Recording stays paused until you resume it.',resume_camera:'Resume motion recording? The camera will restart and warm up. Temperature logging continues.'};
export default function RebootControl(){
 const [state,setState]=useState(null),[confirm,setConfirm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[id,setId]=useState(null);
 async function load(){try{const r=await fetch('/api/reboot',{cache:'no-store'});if(!r.ok)throw Error('Device status unavailable.');setState(await r.json());}catch(e){setState(null);setError(e.message);}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t);},[]);
 function choose(action){setConfirm(action);setId(null);setError('');}
 async function submit(){setBusy(true);setError('');const requestId=id||crypto.randomUUID();setId(requestId);try{const r=await fetch('/api/reboot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,action:confirm})});const d=await r.json();if(!r.ok)throw Error(d.error);setConfirm(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const c=state?.command,action=c?.action||'reboot';
 const expired=c?.status==='queued'&&Date.parse(c.expiresAt)<Date.now();
 const pending=c&&['queued','scheduled'].includes(c.status)&&Date.now()-Date.parse(c.createdAt)<180000;
 const completed={reboot:'Pi restarted and reconnected.',shutdown:'Pi powered on again.',pause_camera:'Camera recording paused. Temperature logging continues.',resume_camera:'Camera recording enabled. The camera is starting; check its status above.'};
 const message=expired?'Request expired; the Pi did not act on it.':c?.status==='queued'?`Requested: ${titles[action]}. Waiting for the Pi…`:c?.status==='completed'?completed[action]:c?.status==='failed'?'The Pi could not complete the request. Please retry.':c?.status==='scheduled'?(action==='shutdown'?'The Pi is shutting down. Reconnect power to start it again.':'Restart scheduled. The Pi will reboot shortly.') :null;
 return <section className="monitoring-reset"><h2>Pi controls</h2><p>Control the Pi and camera. Saved history is retained.</p>{message&&<p role="status">{message}</p>}{!state?.ready&&!pending&&<p className="muted">Controls unavailable: the Pi is offline or setup is incomplete.</p>}{state?.cameraReady&&<p>Camera recording: {state.cameraPaused?'paused':'enabled'}</p>}{confirm?<div><p>{descriptions[confirm]}</p><button disabled={busy} onClick={submit}>{busy?'Requesting…':`Confirm ${titles[confirm]}`}</button>{' '}<button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button></div>:<div><button disabled={!state?.ready||pending} onClick={()=>choose('reboot')}>Reboot Pi…</button>{' '}<button disabled={!state?.shutdownReady||pending} onClick={()=>choose('shutdown')}>Shutdown Pi…</button>{' '}<button disabled={!state?.cameraReady||pending} onClick={()=>choose(state.cameraPaused?'resume_camera':'pause_camera')}>{state?.cameraPaused?'Resume camera…':'Pause camera…'}</button>{state?.ready&&!state?.shutdownReady&&<p className="muted">Shutdown requires one-time setup on the Pi.</p>}</div>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
